//
//  Localization.swift
//  KuaiJi
//
//  本地化字符串辅助
//

import Foundation
import SwiftUI

struct LocaleManager {
    private static let storageKey = "preferred.app.locale"

    static var preferredLocaleIdentifier: String? {
        UserDefaults.standard.string(forKey: storageKey)
    }

    static func updatePreferredLocale(_ identifier: String) {
        UserDefaults.standard.set(identifier, forKey: storageKey)
    }

    static func clearPreferredLocale() {
        UserDefaults.standard.removeObject(forKey: storageKey)
    }
}

extension String {
    var localized: String {
        NSLocalizedString(self, comment: "")
    }
    
    func localized(_ args: CVarArg...) -> String {
        String(format: NSLocalizedString(self, comment: ""), arguments: args)
    }
}

// 本地化键常量
enum L {
    // 通用
    static let ok = "ok"
    static let cancel = "cancel"
    static let done = "done"
    static let save = "save"
    static let delete = "delete"
    static let edit = "edit"
    static let close = "close"
    static let add = "add"
    static let all = "all"
    
    // Tab Bar
    static let tabLedgers = "tab.ledgers"
    static let tabFriends = "tab.friends"
    static let tabSettings = "tab.settings"
    
    // 账本列表
    static let ledgersTitle = "ledgers.title"
    static let ledgersPageTitle = "ledgers.pageTitle"
    static let ledgersNew = "ledgers.new"
    static let ledgersRecentUpdates = "ledgers.recentUpdates"
    static let ledgersArchived = "ledgers.archived"
    static let ledgersArchiveAction = "ledgers.archive"
    static let ledgersUnarchiveAction = "ledgers.unarchive"
    static let ledgersArchivedTag = "ledgers.archived.tag"
    static let ledgersDeleteConfirmTitle = "ledgers.deleteConfirm.title"
    static let ledgersDeleteConfirmMessage = "ledgers.deleteConfirm.message"
    static let ledgersMemberCount = "ledgers.memberCount"
    static let ledgersOutstanding = "ledgers.outstanding"
    
    // 创建账本
    static let createLedgerTitle = "createLedger.title"
    static let createLedgerInfo = "createLedger.ledgerInfo"
    static let createLedgerName = "createLedger.ledgerName"
    static let createLedgerCurrency = "createLedger.currency"
    static let createLedgerMembers = "createLedger.members"
    static let createLedgerSelectFriends = "createLedger.selectFriends"
    static let createLedgerSelectedCount = "createLedger.selectedCount"
    static let createLedgerCreate = "createLedger.create"
    static let createLedgerMe = "createLedger.me"
    
    // 账本详情
    static let ledgerTotalSpent = "ledger.totalSpent"
    static let ledgerMembers = "ledger.members"
    static let ledgerNetAmount = "ledger.netAmount"
    static let ledgerAddExpense = "ledger.addExpense"
    static let ledgerViewRecords = "ledger.viewRecords"
    static let ledgerGeneratePlan = "ledger.generatePlan"
    static let ledgerMember = "ledger.member"
    static let ledgerBalances = "ledger.balances"
    
    // 添加支出
    static let expenseTitle = "expense.title"
    static let expenseBasicInfo = "expense.basicInfo"
    static let expensePurpose = "expense.purpose"
    static let expensePurposePlaceholder = "expense.purposePlaceholder"
    static let expenseDate = "expense.date"
    static let expenseAmount = "expense.amount"
    static let expenseCategory = "expense.category"
    static let expenseParticipants = "expense.participants"
    static let expenseNoMembers = "expense.noMembers"
    static let expenseSplitMethod = "expense.splitMethod"
    static let expensePreview = "expense.preview"
    static let incomeSource = "income.source"
    
    // 分账方式
    static let splitMeAllAA = "split.meAllAA"
    static let splitMeAllAADesc = "split.meAllAA.desc"
    static let splitOtherAllAA = "split.otherAllAA"
    static let splitOtherAllAADesc = "split.otherAllAA.desc"
    static let splitMeTreat = "split.meTreat"
    static let splitMeTreatDesc = "split.meTreat.desc"
    static let splitOtherTreat = "split.otherTreat"
    static let splitOtherTreatDesc = "split.otherTreat.desc"
    static let splitHelpPay = "split.helpPay"
    static let splitHelpPayDesc = "split.helpPay.desc"
    static let splitPayer = "split.payer"
    static let splitSelectPayer = "split.selectPayer"
    static let splitBeneficiary = "split.beneficiary"
    static let splitSelectBeneficiary = "split.selectBeneficiary"
    static let splitAddOtherMembers = "split.addOtherMembers"
    static let splitModeAA = "split.mode.aa"
    static let splitModeTreat = "split.mode.treat"
    static let splitModeWeighted = "split.mode.weighted"
    static let splitModeCustom = "split.mode.custom"
    static let splitModeFixedPlusEqual = "split.mode.fixedPlusEqual"
    static let splitModeHelpPay = "split.mode.helpPay"
    static let splitModeHelpPayWithName = "split.mode.helpPayWithName"
    
    // 分类
    static let categoryFood = "category.food"
    static let categoryTransport = "category.transport"
    static let categoryAccommodation = "category.accommodation"
    static let categoryEntertainment = "category.entertainment"
    static let categoryUtilities = "category.utilities"
    static let categorySelfImprovement = "category.selfImprovement"
    static let categorySchool = "category.school"
    static let categoryMedical = "category.medical"
    static let categoryClothing = "category.clothing"
    static let categoryInvestment = "category.investment"
    static let categorySocial = "category.social"
    static let categoryOther = "category.other"
    
    // 结算
    static let settlementTitle = "settlement.title"
    static let settlementCurrentNet = "settlement.currentNet"
    static let settlementMinTransfers = "settlement.minTransfers"
    static let settlementAllSettled = "settlement.allSettled"
    static let settlementTransfer = "settlement.transfer"
    
    // 流水记录
    static let recordsTitle = "records.title"
    static let recordsEmpty = "records.empty"
    static let recordsEmptyDesc = "records.emptyDesc"
    
    // 朋友
    static let friendsTitle = "friends.title"
    static let friendsAdd = "friends.add"
    static let friendsInfo = "friends.info"
    static let friendsName = "friends.name"
    static let friendsCurrency = "friends.currency"
    static let friendsSelectAvatar = "friends.selectAvatar"
    static let friendsAddTitle = "friends.addTitle"
    static let friendsEditTitle = "friends.editTitle"
    
    // 设置
    static let settingsTitle = "settings.title"
    static let settingsLanguage = "settings.language"
    static let settingsLanguageLabel = "settings.languageLabel"
    static let settingsLanguageDesc = "settings.languageDesc"
    static let settingsQuickActionSection = "settings.quickActionSection"
    static let settingsDefaultLedger = "settings.defaultLedger"
    static let settingsDefaultLedgerNone = "settings.defaultLedgerNone"
    static let settingsDefaultLedgerDesc = "settings.defaultLedgerDesc"
    static let settingsDataSection = "settings.dataSection"
    static let settingsExportData = "settings.exportData"
    static let settingsExportDataDesc = "settings.exportDataDesc"
    static let settingsImportData = "settings.importData"
    static let settingsImportDataDesc = "settings.importDataDesc"
    static let settingsExportSuccess = "settings.exportSuccess"
    static let settingsExportError = "settings.exportError"
    static let settingsExportErrorMessage = "settings.exportErrorMessage"
    static let settingsImportSuccess = "settings.importSuccess"
    static let settingsImportSuccessMessage = "settings.importSuccessMessage"
    static let settingsImportError = "settings.importError"
    static let settingsImportConfirmTitle = "settings.importConfirmTitle"
    static let settingsImportConfirmMessage = "settings.importConfirmMessage"
    static let settingsImportConfirmButton = "settings.importConfirmButton"
    static let settingsAbout = "settings.about"
    static let settingsGuide = "settings.guide"
    static let settingsUsageGuide = "settings.usageGuide"
    static let settingsContactMe = "settings.contactMe"
    static let settingsSupportMe = "settings.supportMe"
    static let settingsRateApp = "settings.rateApp"
    static let settingsVersion = "settings.version"
    static let settingsClearData = "settings.clearData"
    static let settingsClearDataWarning = "settings.clearDataWarning"
    static let settingsConfirmDelete = "settings.confirmDelete"
    static let settingsDeleteMessage = "settings.deleteMessage"
    static let settingsInterfaceDisplay = "settings.interfaceDisplay"
    static let settingsShowSharedAndFriends = "settings.showSharedAndFriends"
    static let settingsShowPersonalLedger = "settings.showPersonalLedger"
    static let settingsSharedLanding = "settings.sharedLanding"
    static let settingsSharedLandingList = "settings.sharedLanding.list"
    static let settingsQuickActionPersonal = "settings.quickActionPersonal"
    static let settingsExportSharedCSV = "settings.exportSharedCSV"
    static let settingsExportSharedCSVEmptyTitle = "settings.exportSharedCSV.emptyTitle"
    static let settingsExportSharedCSVEmptyMessage = "settings.exportSharedCSV.emptyMessage"
    static let settingsExportSharedCSVNotFound = "settings.exportSharedCSV.notFound"
    
    // Support Me
    static let supportTitle = "support.title"
    static let supportSubtitle = "support.subtitle"
    static let supportDisclaimer = "support.disclaimer"
    static let supportNoFeatureNote = "support.noFeatureNote"
    static let supportCoffee = "support.coffee"
    static let supportCheesecake = "support.cheesecake"
    static let supportSushi = "support.sushi"
    static let supportPurchaseTitle = "support.purchase.title"
    static let supportPurchaseSuccess = "support.purchase.success"
    static let supportPurchaseFailed = "support.purchase.failed"
    static let supportPurchaseCancelled = "support.purchase.cancelled"
    static let supportPurchasePending = "support.purchase.pending"
    static let supportSuccess = "support.success"

    // Rate App
    static let rateTitle = "rate.title"
    static let rateSubtitle = "rate.subtitle"
    static let rateInAppAction = "rate.inAppAction"
    static let rateReviewPlaceholder = "rate.reviewPlaceholder"
    static let rateCopyHint = "rate.copyHint"
    static let rateWriteReview = "rate.writeReview"
    static let rateCopied = "rate.copied"
    static let rateStoreMissingTitle = "rate.storeMissing.title"
    static let rateStoreMissingMessage = "rate.storeMissing.message"

    // Quick Actions
    static let quickActionAddExpense = "quickAction.addExpense"
    static let quickActionPersonalSubtitle = "quickAction.personalSubtitle"
    static let quickActionBackupReminder = "quickAction.backupReminder"
    
    // 语言选项
    static let languageSystem = "language.system"
    static let languageChinese = "language.chinese"
    static let languageEnglish = "language.english"
    static let languageFrench = "language.french"
    

    // 个人账本
    static let tabPersonalLedger = "tab.personalLedger"
    static let personalHomeTitle = "personal.homeTitle"
    static let personalTodayTitle = "personal.todayTitle"
    static let personalTodayEmpty = "personal.todayEmpty"
    static let personalDeleteConfirm = "personal.deleteConfirm"
    static let personalThisMonth = "personal.thisMonth"
    static let personalMonthlyExpense = "personal.monthlyExpense"
    static let personalMonthlyIncome = "personal.monthlyIncome"
    static let personalArchiveTitle = "personal.archive.title"
    static let personalArchiveLoading = "personal.archive.loading"
    static let personalArchiveEmpty = "personal.archive.empty"
    static let personalArchiveViewRecords = "personal.archive.viewRecords"
    static let personalDetailSection = "personal.detail.section"
    static let personalDetailCategory = "personal.detail.category"
    static let personalDetailAccount = "personal.detail.account"
    static let personalDetailType = "personal.detail.type"
    static let personalDetailAmount = "personal.detail.amount"
    static let personalDetailDate = "personal.detail.date"
    static let personalDetailNote = "personal.detail.note"
    static let personalTypeIncome = "personal.type.income"
    static let personalTypeExpense = "personal.type.expense"
    static let personalTypeFee = "personal.type.fee"
    static let personalFieldType = "personal.field.type"
    static let personalFieldAccount = "personal.field.account"
    static let personalFieldCurrency = "personal.field.currency"
    static let personalFieldCategory = "personal.field.category"
    static let personalFieldAmount = "personal.field.amount"
    static let personalFieldFXRate = "personal.field.fxRate"
    static let personalFieldDate = "personal.field.date"
    static let personalFieldNote = "personal.field.note"
    static let personalFieldAttachment = "personal.field.attachment"
    static let personalFieldPickPhoto = "personal.field.pickPhoto"
    static let personalAllRecordsTitle = "personal.allRecords.title"
    static let personalFilterTitle = "personal.filter.title"
    static let personalFilterFrom = "personal.filter.from"
    static let personalFilterTo = "personal.filter.to"
    static let personalFilterKeyword = "personal.filter.keyword"
    static let personalFilterMin = "personal.filter.min"
    static let personalFilterMax = "personal.filter.max"
    static let personalSaveAndShare = "personal.saveAndShare"
    static let personalSaveAndShareSheetTitle = "personal.saveAndShare.sheetTitle"
    static let personalSaveAndShareLedgerSection = "personal.saveAndShare.ledgerSection"
    static let personalSaveAndShareSplitMode = "personal.saveAndShare.splitMode"
    static let personalSaveAndShareSummary = "personal.saveAndShare.summary"
    static let personalSaveAndShareNoLedgers = "personal.saveAndShare.noLedgers"
    static let personalSaveAndShareModeEqual = "personal.saveAndShare.mode.equal"
    static let personalSaveAndShareModeTreat = "personal.saveAndShare.mode.treat"
    static let personalSaveAndShareCurrencyMismatch = "personal.saveAndShare.currencyMismatch"
    static let personalSaveAndShareUnavailable = "personal.saveAndShare.unavailable"
    static let personalSaveAndShareLedgerMissing = "personal.saveAndShare.ledgerMissing"
    static let personalSaveAndShareMissingCurrentUser = "personal.saveAndShare.missingCurrentUser"
    static let personalSaveAndShareMembersMissing = "personal.saveAndShare.membersMissing"
    static let personalSaveAndShareInvalidAmount = "personal.saveAndShare.invalidAmount"
    static let personalSaveAndShareOpenFullSplit = "personal.saveAndShare.openFullSplit"
    static let personalExportFailed = "personal.export.failed"
    static let personalAccountsSummary = "personal.accounts.summary"
    static let personalNetWorth = "personal.netWorth"
    static let personalNetWorthEmpty = "personal.netWorth.empty"
    static let personalShowArchived = "personal.showArchived"
    static let personalAccountsList = "personal.accounts.list"
    static let personalAccountsTitle = "personal.accounts.title"
    static let personalAccountTypeBank = "personal.accountType.bank"
    static let personalAccountTypeMobile = "personal.accountType.mobile"
    static let personalAccountTypeCash = "personal.accountType.cash"
    static let personalAccountTypeCredit = "personal.accountType.credit"
    static let personalAccountTypePrepaid = "personal.accountType.prepaid"
    static let personalAccountTypeOther = "personal.accountType.other"
    static let personalArchive = "personal.archive"
    static let personalActivate = "personal.activate"
    static let personalTransferAccounts = "personal.transfer.accounts"
    static let personalTransferFrom = "personal.transfer.from"
    static let personalTransferTo = "personal.transfer.to"
    static let personalTransferAmount = "personal.transfer.amount"
    static let personalTransferFee = "personal.transfer.fee"
    static let personalTransferFeeSide = "personal.transfer.feeSide"
    static let personalTransferFeeFrom = "personal.transfer.feeFrom"
    static let personalTransferFeeTo = "personal.transfer.feeTo"
    static let personalFieldFee = "personal.field.fee"
    static let personalStatsTitle = "personal.stats.title"
    static let personalStatsPeriod = "personal.stats.period"
    static let personalStatsIncludeFee = "personal.stats.includeFee"
    static let personalStatsMonth = "personal.stats.month"
    static let personalStatsQuarter = "personal.stats.quarter"
    static let personalStatsYear = "personal.stats.year"
    static let personalStatsExpenseGrowth = "personal.stats.expenseGrowth"
    static let personalStatsIncomeGrowth = "personal.stats.incomeGrowth"
    static let personalStatsGrowthDetail = "personal.stats.growth.detail"
    static let personalStatsGrowthDetailFull = "personal.stats.growth.detail.full"
    static let personalStatsGrowthUp = "personal.stats.growth.up"
    static let personalStatsGrowthDown = "personal.stats.growth.down"
    static let personalStatsCategoryClickHint = "personal.stats.categoryClickHint"
    static let personalStatsChartShare = "personal.stats.chart.share"
    static let personalStatsChartIncome = "personal.stats.chart.income"
    static let personalStatsChartExpense = "personal.stats.chart.expense"
    static let personalStatsChartDate = "personal.stats.chart.date"
    static let personalStatsChartCategory = "personal.stats.chart.category"
    static let personalStatsChartAmount = "personal.stats.chart.amount"
    static let personalStatsFocusExpense = "personal.stats.focus.expense"
    static let personalStatsFocusIncome = "personal.stats.focus.income"
    static let personalStatsEmpty = "personal.stats.empty"
    static let personalStatsRecordCount = "personal.stats.recordCount"
    static let personalSettingsTitle = "personal.settings.title"
    static let personalPrimaryCurrency = "personal.primaryCurrency"
    static let personalFXSource = "personal.fxSource"
    static let personalFXPrecision = "personal.fxPrecision"
    static let personalFXDefaultRate = "personal.fxDefaultRate"
    static let personalDefaultFee = "personal.defaultFee"
    static let personalFeeInclude = "personal.feeInclude"
    static let personalFieldCreditLimit = "personal.field.creditLimit"
    static let personalFXPlaceholder = "personal.fxPlaceholder"
    static let personalFeePlaceholder = "personal.feePlaceholder"
    static let personalAccountsManage = "personal.accounts.manage"
    static let personalTemplatesTitle = "personal.templates.title"
    static let personalTemplatesCreate = "personal.templates.create"
    static let personalTemplatesEmpty = "personal.templates.empty"
    static let personalTemplatesQuickFill = "personal.templates.quickFill"
    static let personalTemplatesQuickFillHint = "personal.templates.quickFillHint"
    static let personalTemplatesName = "personal.templates.name"
    static let personalTemplatesNoAccount = "personal.templates.noAccount"
    static let personalTemplatesNoCategory = "personal.templates.noCategory"
    static let personalTemplatesNoAmount = "personal.templates.noAmount"
    static let personalTemplatesOptionalHint = "personal.templates.optionalHint"
    static let personalCategoriesManage = "personal.categories.manage"
    static let personalCategoriesSystem = "personal.categories.system"
    static let personalCategoriesCustom = "personal.categories.custom"
    static let personalCategoriesAdd = "personal.categories.add"
    static let personalCategoriesEmpty = "personal.categories.empty"
    static let personalCategoriesName = "personal.categories.name"
    static let personalCategoriesNamePlaceholder = "personal.categories.namePlaceholder"
    static let personalCategoriesType = "personal.categories.type"
    static let personalCategoriesColor = "personal.categories.color"
    static let personalCategoriesIcon = "personal.categories.icon"
    static let personalCategoriesSymbolPlaceholder = "personal.categories.symbolPlaceholder"
    static let personalCategoriesSymbolHint = "personal.categories.symbolHint"
    static let personalCategoriesInvalidSymbol = "personal.categories.invalidSymbol"
    static let personalCategoriesPreview = "personal.categories.preview"
    static let personalCategoriesMapping = "personal.categories.mapping"
    static let personalCategoriesMappingHint = "personal.categories.mappingHint"
    static let personalCategoriesMappingNone = "personal.categories.mapping.none"
    static let personalCategoriesMappingValue = "personal.categories.mapping.value"
    static let personalCategoryMappingTitle = "personal.category.mapping.title"
    static let personalCategoryMappingRequired = "personal.category.mapping.required"
    static let personalCategoriesHide = "personal.categories.hide"
    static let personalSymbolGroupCommon = "personal.symbolGroup.common"
    static let personalSymbolGroupLife = "personal.symbolGroup.life"
    static let personalSymbolGroupTravel = "personal.symbolGroup.travel"
    static let personalSymbolGroupFinance = "personal.symbolGroup.finance"
    static let personalSymbolGroupFun = "personal.symbolGroup.fun"
    static let personalSymbolGroupWork = "personal.symbolGroup.work"
    static let personalSymbolNameTag = "personal.symbolName.tag"
    static let personalSymbolNameBookmark = "personal.symbolName.bookmark"
    static let personalSymbolNameBell = "personal.symbolName.bell"
    static let personalSymbolNameCalendar = "personal.symbolName.calendar"
    static let personalSymbolNameTray = "personal.symbolName.tray"
    static let personalSymbolNameHeart = "personal.symbolName.heart"
    static let personalSymbolNameLeaf = "personal.symbolName.leaf"
    static let personalSymbolNameCup = "personal.symbolName.cup"
    static let personalSymbolNameHouse = "personal.symbolName.house"
    static let personalSymbolNameCart = "personal.symbolName.cart"
    static let personalSymbolNameWater = "personal.symbolName.water"
    static let personalSymbolNameCar = "personal.symbolName.car"
    static let personalSymbolNameTram = "personal.symbolName.tram"
    static let personalSymbolNameBike = "personal.symbolName.bike"
    static let personalSymbolNamePlane = "personal.symbolName.plane"
    static let personalSymbolNameFuel = "personal.symbolName.fuel"
    static let personalSymbolNameSuitcase = "personal.symbolName.suitcase"
    static let personalSymbolNameMap = "personal.symbolName.map"
    static let personalSymbolNameCash = "personal.symbolName.cash"
    static let personalSymbolNameCard = "personal.symbolName.card"
    static let personalSymbolNameDollar = "personal.symbolName.dollar"
    static let personalSymbolNameChart = "personal.symbolName.chart"
    static let personalSymbolNameBitcoin = "personal.symbolName.bitcoin"
    static let personalSymbolNameWallet = "personal.symbolName.wallet"
    static let personalSymbolNameGiftcard = "personal.symbolName.giftcard"
    static let personalSymbolNameGame = "personal.symbolName.game"
    static let personalSymbolNameMusic = "personal.symbolName.music"
    static let personalSymbolNameFilm = "personal.symbolName.film"
    static let personalSymbolNameTicket = "personal.symbolName.ticket"
    static let personalSymbolNameSparkles = "personal.symbolName.sparkles"
    static let personalSymbolNamePalette = "personal.symbolName.palette"
    static let personalSymbolNameParty = "personal.symbolName.party"
    static let personalSymbolNameBriefcase = "personal.symbolName.briefcase"
    static let personalSymbolNameLaptop = "personal.symbolName.laptop"
    static let personalSymbolNameDoc = "personal.symbolName.doc"
    static let personalSymbolNamePersons = "personal.symbolName.persons"
    static let personalSymbolNamePaperclip = "personal.symbolName.paperclip"
    static let personalSymbolNameHammer = "personal.symbolName.hammer"
    static let personalSymbolNameBuilding = "personal.symbolName.building"
    static let personalUsageScenarios = "personal.usage.scenarios"
    static let personalUsagePhilosophy = "personal.usage.philosophy"
    static let personalUsageFlowsTitle = "personal.usage.flows.title"
    static let personalUsageFlow1 = "personal.usage.flow1"
    static let personalUsageFlow2 = "personal.usage.flow2"
    static let personalUsageFlow3 = "personal.usage.flow3"
    static let personalUsageFlow4 = "personal.usage.flow4"
    static let personalUsageFlow1Step1 = "personal.usage.flow1.step1"
    static let personalUsageFlow1Step2 = "personal.usage.flow1.step2"
    static let personalUsageFlow1Step3 = "personal.usage.flow1.step3"
    static let personalUsageFlow1Step4 = "personal.usage.flow1.step4"
    static let personalUsageFlow1Step5 = "personal.usage.flow1.step5"
    static let personalUsageFlow1Step6 = "personal.usage.flow1.step6"
    static let personalUsageFlow2Step1 = "personal.usage.flow2.step1"
    static let personalUsageFlow2Step2 = "personal.usage.flow2.step2"
    static let personalUsageFlow2Step3 = "personal.usage.flow2.step3"
    static let personalUsageFlow2Step4 = "personal.usage.flow2.step4"
    static let personalUsageFlow3Step1 = "personal.usage.flow3.step1"
    static let personalUsageFlow3Step2 = "personal.usage.flow3.step2"
    static let personalUsageFlow3Step3 = "personal.usage.flow3.step3"
    static let personalUsageFlow3Step4 = "personal.usage.flow3.step4"
    static let personalUsageFlow3Step5 = "personal.usage.flow3.step5"
    static let personalUsageFlow4Step1 = "personal.usage.flow4.step1"
    static let personalUsageFlow4Step2 = "personal.usage.flow4.step2"
    static let personalUsageFlow4Step3 = "personal.usage.flow4.step3"
    static let personalUsageFlow4Step4 = "personal.usage.flow4.step4"
    static let personalUsageFlowSummary = "personal.usage.flow.summary"
    static let personalUsageDesignTitle = "personal.usage.design.title"
    static let personalUsageDesign1 = "personal.usage.design1"
    static let personalUsageDesign2 = "personal.usage.design2"
    static let personalUsageDesign3 = "personal.usage.design3"
    static let personalUsageDesign4 = "personal.usage.design4"
    static let personalUsageDesign5 = "personal.usage.design5"
    static let personalSortOccurred = "personal.sort.occurred"
    static let personalSortCreated = "personal.sort.created"
    static let personalTransferTitle = "personal.transfer.title"
    static let personalTransferDirection = "personal.transfer.direction"
    static let personalTransferDirectionTitle = "personal.transfer.directionTitle"
    static let personalTransferInvert = "personal.transfer.invert"
    static let personalTransferFeeHint = "personal.transfer.feeHint"
    static let personalTransferFXInfo = "personal.transfer.fxInfo"
    static let personalConversionFeeNote = "personal.conversionFeeNote"
    static let personalExportHint = "personal.export.hint"
    static let personalClearHint = "personal.clear.hint"
    static let personalAccountTypeLabel = "personal.accountType.label"
    static let personalDataSection = "personal.data.section"
    static let personalExportCSV = "personal.exportCSV"
    static let personalExportUntil = "personal.export.until"
    static let personalClearData = "personal.clearData"
    static let personalClearConfirmTitle = "personal.clear.confirmTitle"
    static let personalClearConfirmMessage = "personal.clear.confirmMessage"
    static let personalClearSuccess = "personal.clear.success"
    static let personalClearSuccessMessage = "personal.clear.successMessage"
    static let personalClearFailed = "personal.clear.failed"
    static let personalFXSourceManual = "personal.fxSource.manual"
    static let personalFXSourceFixed = "personal.fxSource.fixed"
    static let personalFieldName = "personal.field.name"
    static let personalFieldBalance = "personal.field.balance"
    static let personalAccountStatus = "personal.accountStatus"
    static let personalStatusActive = "personal.status.active"
    static let personalStatusArchived = "personal.status.archived"
    static let personalIncludeInNet = "personal.includeInNet"
    // 联系页面
    static let contactAuthor = "contact.author"
    static let contactEmail = "contact.email"
    static let contactRednote = "contact.rednote"
    static let contactGithub = "contact.github"
    static let contactSupport = "contact.support"
    static let contactEmailSubtitle = "contact.email.subtitle"
    static let contactRednoteSubtitle = "contact.rednote.subtitle"
    static let contactGithubSubtitle = "contact.github.subtitle"
    static let contactSupportSubtitle = "contact.support.subtitle"
    
    // 首次设置
    static let onboardingTitle = "onboarding.title"
    static let onboardingDescription = "onboarding.description"
    static let onboardingNameSection = "onboarding.nameSection"
    static let onboardingNamePlaceholder = "onboarding.namePlaceholder"
    static let onboardingNameFooter = "onboarding.nameFooter"
    static let onboardingCurrencySection = "onboarding.currencySection"
    static let onboardingCurrencyPicker = "onboarding.currencyPicker"
    static let onboardingCurrencyFooter = "onboarding.currencyFooter"
    static let onboardingCurrencyCNY = "onboarding.currency.cny"
    static let onboardingCurrencyUSD = "onboarding.currency.usd"
    static let onboardingCurrencyEUR = "onboarding.currency.eur"
    static let onboardingAvatarSection = "onboarding.avatarSection"
    static let onboardingCurrentAvatar = "onboarding.currentAvatar"
    static let onboardingAvatarFooter = "onboarding.avatarFooter"
    static let onboardingAllEmojis = "onboarding.allEmojis"
    static let onboardingStartButton = "onboarding.startButton"
    static let onboardingCompleteFooter = "onboarding.completeFooter"
    static let onboardingErrorTitle = "onboarding.errorTitle"
    static let onboardingErrorMessage = "onboarding.errorMessage"
    
    // 个人资料
    static let profileTitle = "profile.title"
    static let profileEdit = "profile.edit"
    static let profileViewInfo = "profile.viewInfo"
    static let profileName = "profile.name"
    static let profileNamePlaceholder = "profile.namePlaceholder"
    static let profileNameFooter = "profile.nameFooter"
    static let profileCurrency = "profile.currency"
    static let profileCurrencyPicker = "profile.currencyPicker"
    static let profileAvatar = "profile.avatar"
    static let profileCurrentAvatar = "profile.currentAvatar"
    static let profileAvatarFooter = "profile.avatarFooter"
    static let profileUserIdLabel = "profile.userIdLabel"
    static let profileCurrencyLabel = "profile.currencyLabel"
    
    // 二维码
    static let qrcodeMyTitle = "qrcode.myTitle"
    static let qrcodeScanInstruction = "qrcode.scanInstruction"
    static let qrcodeScannerTitle = "qrcode.scannerTitle"
    static let qrcodeScannerInstruction = "qrcode.scannerInstruction"
    static let qrcodeScanError = "qrcode.scanError"
    static let qrcodeInvalidFormat = "qrcode.invalidFormat"
    static let qrcodeCannotAddSelf = "qrcode.cannotAddSelf"
    static let qrcodeAlertTitle = "qrcode.alertTitle"
    static let qrcodeCameraError = "qrcode.cameraError"
    static let qrcodeCameraInitError = "qrcode.cameraInitError"
    static let qrcodeCameraInputError = "qrcode.cameraInputError"
    static let qrcodeMetadataOutputError = "qrcode.metadataOutputError"
    
    // 朋友菜单
    static let friendMenuManualInput = "friendMenu.manualInput"
    static let friendMenuMyQRCode = "friendMenu.myQRCode"
    static let friendMenuScanQRCode = "friendMenu.scanQRCode"
    
    // 账本页面卡片
    static let ledgerCardTotalExpenses = "ledger.card.totalExpenses"
    static let ledgerCardMemberExpenses = "ledger.card.memberExpenses"
    static let ledgerCardRecentRecords = "ledger.card.recentRecords"
    static let ledgerCardAllButton = "ledger.card.allButton"
    static let ledgerCardNoRecords = "ledger.card.noRecords"
    static let ledgerCardMemberTotalSpent = "ledger.card.memberTotalSpent"
    static let ledgerCardViewTransferPlan = "ledger.card.viewTransferPlan"
    static let ledgerCardClearBalances = "ledger.card.clearBalances"
    
    // 清账功能
    static let clearBalancesConfirmTitle = "clearBalances.confirmTitle"
    static let clearBalancesConfirmMessage = "clearBalances.confirmMessage"
    static let clearBalancesConfirmButton = "clearBalances.confirmButton"
    
    // 所有成员页面
    static let allMembersTitle = "allMembers.title"
    static let allMembersTotalSpent = "allMembers.totalSpent"
    
    // 支出验证
    static let expenseValidationMinAmount = "expense.validation.minAmount"
    static let expenseOptionalFields = "expense.optionalFields"
    
    // 错误提示
    static let errorAmountMustBePositive = "error.amount.positive"
    static let errorAccountRequired = "error.account.required"
    static let errorTemplateNameRequired = "error.template.nameRequired"
    
    // 默认值
    static let defaultUnknown = "default.unknown"
    static let defaultUnknownMember = "default.unknownMember"
    static let defaultUntitledExpense = "default.untitledExpense"
    static let defaultPreview = "default.preview"
    static let defaultNewLedger = "default.newLedger"
    static let defaultClearBalanceTransfer = "default.clearBalanceTransfer"
    static let defaultClearBalanceNote = "default.clearBalanceNote"
    
    // 数据同步
    static let syncTitle = "sync.title"
    static let syncImportantWarning = "sync.importantWarning"
    static let syncWarningTitle = "sync.warningTitle"
    static let syncWarningMessage = "sync.warningMessage"
    static let syncWarningConfirm = "sync.warningConfirm"
    static let syncWarningConfirmNoRemind = "sync.warningConfirmNoRemind"
    static let syncWarning1 = "sync.warning1"
    static let syncWarning2 = "sync.warning2"
    static let syncWarning3 = "sync.warning3"
    static let syncWarning4 = "sync.warning4"
    static let syncRecommendation = "sync.recommendation"
    static let syncStatus = "sync.status"
    static let syncDiscovering = "sync.discovering"
    static let syncNotStarted = "sync.notStarted"
    static let syncConnectedDevices = "sync.connectedDevices"
    static let syncNearbyDevices = "sync.nearbyDevices"
    static let syncNoDevicesFound = "sync.noDevicesFound"
    static let syncConnect = "sync.connect"
    static let syncStartDiscovery = "sync.startDiscovery"
    static let syncStopDiscovery = "sync.stopDiscovery"
    static let syncStartSync = "sync.startSync"
    static let syncConfirmStart = "sync.confirmStart"
    static let syncResultTitle = "sync.resultTitle"
    static let syncMenuTitle = "sync.menuTitle"
    static let syncResultAddedLedgers = "sync.result.addedLedgers"
    static let syncResultUpdatedLedgers = "sync.result.updatedLedgers"
    static let syncResultAddedExpenses = "sync.result.addedExpenses"
    static let syncResultAddedFriends = "sync.result.addedFriends"
    static let syncResultErrors = "sync.result.errors"
    static let syncResultNoUpdates = "sync.result.noUpdates"
    static let syncDeviceAvailable = "sync.deviceAvailable"
    static let syncDeviceConnected = "sync.deviceConnected"
    static let syncCurrentDevice = "sync.currentDevice"
    static let syncShareLedger = "sync.shareLedger"
    static let syncCompleted = "sync.completed"
    static let syncWaitingResponse = "sync.waitingResponse"
    static let syncBidirectionalComplete = "sync.bidirectionalComplete"
    static let syncReceivedFrom = "sync.receivedFrom"
    static let syncSentBack = "sync.sentBack"
    static let syncSendBackError = "sync.sendBackError"
    static let syncErrorPreparing = "sync.errorPreparing"
    static let syncErrorEncoding = "sync.errorEncoding"
    static let syncErrorInvalidData = "sync.errorInvalidData"

    // 全量抹除
    static let eraseAllData = "eraseAllData"
    static let eraseAllDataWarning = "eraseAllData.warning"
    static let eraseAllConfirmTitle = "eraseAllData.confirmTitle"
    static let eraseAllConfirmMessage = "eraseAllData.confirmMessage"
    
    // 欢迎引导
    static let guideWelcomeTitle = "guide.welcome.title"
    static let guideWelcomeDesc = "guide.welcome.desc"
    static let guideFriendsTitle = "guide.friends.title"
    static let guideFriendsDesc = "guide.friends.desc"
    static let guideLedgerTitle = "guide.ledger.title"
    static let guideLedgerDesc = "guide.ledger.desc"
    static let guideSyncTitle = "guide.sync.title"
    static let guideSyncDesc = "guide.sync.desc"
    static let guidePrivacyTitle = "guide.privacy.title"
    static let guidePrivacyDesc = "guide.privacy.desc"
    static let guideSkip = "guide.skip"
    static let guideNext = "guide.next"
    static let guidePrevious = "guide.previous"
    static let guideStart = "guide.start"
    // 引导页面视觉元素
    static let guideScanQRCode = "guide.scanQRCode"
    static let guideBecomeFriends = "guide.becomeFriends"
    static let guideExampleTrip = "guide.exampleTrip"
    static let guideExampleDinner = "guide.exampleDinner"
    static let guideYourDevice = "guide.yourDevice"
    static let guideFriendDevice = "guide.friendDevice"
    static let guideLocalStorage = "guide.localStorage"
    static let guideNoServer = "guide.noServer"
    static let guideFullyPrivate = "guide.fullyPrivate"
    // 引导页面示例金额
    static let guideSampleAmount1 = "guide.sample.amount1"
    static let guideSampleAmount2 = "guide.sample.amount2"

    // 新增：朋友页补充 & 个人账本独立性说明
    static let guideFriendsSyncTip = "guide.friends.syncTip"
    static let guidePersonalIntroTitle = "guide.personalIntro.title"
    static let guidePersonalIntroDesc = "guide.personalIntro.desc"
    static let guideIndependenceTitle = "guide.independence.title"
    static let guideIndependenceDesc = "guide.independence.desc"
    
    // 配色方案
    static let settingsColorScheme = "settings.colorScheme"
    static let themeDefault = "theme.default"
    static let themeForest = "theme.forest"
    static let themePeach = "theme.peach"
    static let themeLavender = "theme.lavender"
    static let themeAlps = "theme.alps"
    static let themeMorandi = "theme.morandi"
    static let themeChristmas = "theme.christmas"
}
